In [2]:
import numpy
# compare each values in vector with the specific value 10
vector = numpy.array([5,10,15,20])
vector == 10

array([False,  True, False, False], dtype=bool)

In [3]:
# same idea
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [5]:
vector = numpy.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])

[False  True False False]
[10]


In [6]:
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
second_column_25 = (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25,:])

[False  True False]
[[20 25 30]]


In [7]:
# perform comparrisons with multiple conditions
vector = numpy.array([5,10,15,20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [8]:
vector = numpy.array([5,10,15,20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [10]:
vector = numpy.array([5,10,15,20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [11]:
# we can convert the data type of an array with the ndarray.astype() method
vector = numpy.array(["1","2","3"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[ 1.  2.  3.]


In [12]:
vector = numpy.array([5,10,15,20])
vector.min()
# print(help(numpy.array))

5

In [13]:
# the axis indicates which dimension we perform the operation
# 1 means that we want to perform the operation on each row, and 0 means on each column
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
matrix.sum(axis=1)

array([ 30,  75, 120])

In [14]:
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
matrix.sum(axis=0)

array([60, 75, 90])