In [1]:
import numpy
test = numpy.genfromtxt("test.txt", delimiter=",",dtype=str)
print(type(test))
print(test)
print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
['hello world' 'Hongyu Wu']
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Mote
        that generators must return byte strings in Python 

In [3]:
# np.array take a list or list of lists as input. 
# when input a list, we get one-dimensional array
vector = numpy.array([5,10,15,20])
# when input a list of lists, we gt a matrix
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
# ndarray.shape property to figure out how many elements are in the array
vector = numpy.array([1,2,3,4])
print(vector.shape)
# for matrices, the shape property contains a tuple with 2 elements:row and column
matrix = numpy.array([[5,10,15],[20,25,30]])
print(matrix.shape)

(4,)
(2, 3)


In [9]:
# each value in a np array has to have the same type
# np will automatically figure out an apprortiate data type when reading in data or converting lists to array
# we can check the data type of a np array using dtype property
numbers = numpy.array([1,2,3,4.0])
print(numbers)
numbers.dtype

[ 1.  2.  3.  4.]


dtype('float64')

In [ ]:
# np cannot convert a value to a numeric data type like float or integer, it uses a special nan
# nan is the missing data
# 1.986000e+03 is actually 1.986 * 10^3


In [12]:
test = numpy.genfromtxt("test.txt", delimiter=",",dtype=str,skip_header = 0)
print(test)

[['hello world' ' I am' ' Wu' ' hong' '12']
 ['Hongyu Wu' 'age' '24' 'not married' '33']]


In [16]:
a = test[0,1]
b = test[1,2]
print(a)
print(b)

 I am
24


In [17]:
vector = numpy.array([1,2,3,4])
print(vector[0:3])

[1 2 3]


In [18]:
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
print(matrix[:,1])

[10 25 40]


In [19]:
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [20]:
matrix = numpy.array([[5,10,15],
                      [20,25,30],
                      [35,40,45]])
print(matrix[1:3,0:2])

[[20 25]
 [35 40]]
