In [3]:
import numpy as np
A = np.arange(3)
print(A)
print(np.exp(A)) #e^A
print(np.sqrt(A)) 


[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [10]:
# return the floor of the input
a = 10*np.random.random((3,4))
print(a)
a = np.floor(a)
print('-----')
print(a)
print('-----')
print(a.ravel())#flatten the array
print('-----')
a.shape = (6,2)
print(a)
print('-----')
print(a.T)

[[ 8.75665468  9.65380412  3.07755079  7.48609127]
 [ 5.14029225  1.26396774  7.83848587  2.50626543]
 [ 6.22043636  1.04047809  5.26436005  2.13109026]]
-----
[[ 8.  9.  3.  7.]
 [ 5.  1.  7.  2.]
 [ 6.  1.  5.  2.]]
-----
[ 8.  9.  3.  7.  5.  1.  7.  2.  6.  1.  5.  2.]
-----
[[ 8.  9.]
 [ 3.  7.]
 [ 5.  1.]
 [ 7.  2.]
 [ 6.  1.]
 [ 5.  2.]]
-----
[[ 8.  3.  5.  7.  6.  5.]
 [ 9.  7.  1.  2.  1.  2.]]


In [13]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))      
print(a)
print('-----')
print(b)
print('-----')
print(np.vstack((a,b)))
print('-----')
print(np.hstack((a,b)))

[[ 3.  9.]
 [ 2.  9.]]
-----
[[ 6.  2.]
 [ 2.  8.]]
-----
[[ 3.  9.]
 [ 2.  9.]
 [ 6.  2.]
 [ 2.  8.]]
-----
[[ 3.  9.  6.  2.]
 [ 2.  9.  2.  8.]]


In [16]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print('-----')
print(np.hsplit(a,3))
print('-----')
print(np.hsplit(a,(3,4))) #split after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print('-----')
print(a)
print(np.vsplit(a,3))

[[ 7.  3.  2.  0.  9.  5.  0.  0.  9.  3.  0.  5.]
 [ 4.  1.  1.  8.  7.  1.  4.  8.  5.  5.  6.  0.]]
-----
[array([[ 7.,  3.,  2.,  0.],
       [ 4.,  1.,  1.,  8.]]), array([[ 9.,  5.,  0.,  0.],
       [ 7.,  1.,  4.,  8.]]), array([[ 9.,  3.,  0.,  5.],
       [ 5.,  5.,  6.,  0.]])]
-----
[array([[ 7.,  3.,  2.],
       [ 4.,  1.,  1.]]), array([[ 0.],
       [ 8.]]), array([[ 9.,  5.,  0.,  0.,  9.,  3.,  0.,  5.],
       [ 7.,  1.,  4.,  8.,  5.,  5.,  6.,  0.]])]
-----
[[ 5.  0.]
 [ 2.  4.]
 [ 9.  4.]
 [ 6.  8.]
 [ 6.  8.]
 [ 6.  2.]
 [ 6.  5.]
 [ 5.  0.]
 [ 3.  7.]
 [ 4.  9.]
 [ 7.  9.]
 [ 9.  4.]]
[array([[ 5.,  0.],
       [ 2.,  4.],
       [ 9.,  4.],
       [ 6.,  8.]]), array([[ 6.,  8.],
       [ 6.,  2.],
       [ 6.,  5.],
       [ 5.,  0.]]), array([[ 3.,  7.],
       [ 4.,  9.],
       [ 7.,  9.],
       [ 9.,  4.]])]


In [17]:
# simple assignments make no copy of array objects or of their data
a = np.arange(12)
b = a
# a & b are two names for the same ndarray object
print(b is a)
b.shape = 3,4
print(a.shape)
print(id(a))
print(id(b))


True
(3, 4)
2852149776832
2852149776832


In [19]:
# the view method creates a new array object that looks at the same data
c = a.view()
print(c)
print(c is a)
c.shape = 2,6
print(c)
print(a.shape)
c[0,4] = 1234
print(a)
print(id(a))
print(id(c))

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
False
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
2852149776832
2852149777952


In [20]:
# the copy method makes a complete copy of the array and its data
d = a.copy() # this is very important when we just want to copy the value of one variable to another.
d is a
d[0,0] = 9999
print(d)
print(a)

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
